#include "struct.h"
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <stdlib.h>
#include <sys/ipc.h>
#include <sys/shm.h>
//#include "memPart2.c"
#include "randGen.c"
#include "fork.c"